### ISSUE TITLE
Extend Clean Architecture to Implement a GraphQL API

### ISSUE THREAD

**Issue by abdullahkhanjmm** [abdullahkhanjmm/dotnet-roadmap-2024#12]
### Extend Clean Architecture to Implement a GraphQL API
---

**Task:**
Extend the previous Clean Architecture .NET project to include a GraphQL API with CRUD operations.

**Overview:**
In this task, you will extend the existing .NET project that follows Clean Architecture principles to include a GraphQL API. This will provide an alternative to the RESTful API, offering more flexibility in querying and manipulating data.

### Clean Architecture Layers

1. **Core (Domain) Layer:**
   - **Entities:** Business models that are independent of any framework or technology.
   - **Interfaces:** Abstractions for services and repositories.
   - **Domain Services:** Business logic that doesn't belong to a specific entity.

2. **Application Layer:**
   - **DTOs (Data Transfer Objects):** Models for transferring data between layers.
   - **Services/Use Cases:** Application-specific business logic.
   - **Interfaces Implementation:** Implementation of domain interfaces.

3. **Infrastructure Layer:**
   - **Data Access:** Repositories and data context for interacting with the database.
   - **External Services:** Integration with external APIs or services.
   - **Configuration:** Application configuration and settings.

4. **Presentation (API) Layer:**
   - **Controllers:** API endpoints to handle HTTP requests and responses.
   - **Models:** API request and response models.
   - **Mapping:** AutoMapper profiles for converting between domain models and DTOs.

### New GraphQL Layer

1. **Core (Domain) Layer:**
   - No additional changes are needed here.

2. **Application Layer:**
   - **GraphQL Queries:** Define the queries that can be made.
   - **GraphQL Mutations:** Define the mutations for creating, updating, and deleting data.
   - **GraphQL Types:** Define the types that represent the data structure.

3. **Infrastructure Layer:**
   - No additional changes are needed here, but make sure your data access layer supports the operations needed by GraphQL.

4. **Presentation (GraphQL) Layer:**
   - **GraphQL Schema:** Define the schema that includes all the queries and mutations.
   - **GraphQL Resolvers:** Implement the resolvers that handle the logic for each query and mutation.
   - **Models:** GraphQL-specific request and response models, if necessary.
   - **Mapping:** AutoMapper profiles for converting between domain models and GraphQL types.

### 1. **Set Up Project:**
   - Ensure you have the necessary packages:
     ```sh
     dotnet add package HotChocolate.AspNetCore
     dotnet add package HotChocolate.Data
     dotnet add package HotChocolate.Types
     ```

### 2. **Define GraphQL Types:**
   - Create GraphQL types for your entities.
     ```csharp
     public class UserType : ObjectType<User>
     {
         protected override void Configure(IObjectTypeDescriptor<User> descriptor)
         {
             descriptor.Field(x => x.Id);
             descriptor.Field(x => x.Name);
             descriptor.Field(x => x.Email);
         }
     }
     ```

### 3. **Define Queries:**
   - Create query classes for reading data.
     ```csharp
     public class Query
     {
         public IQueryable<User> GetUsers([Service] IUserRepository userRepository)
         {
             return userRepository.GetUsers();
         }

         public User GetUserById([Service] IUserRepository userRepository, Guid id)
         {
             return userRepository.GetUserById(id);
         }
     }
     ```
Here are the steps to implement the `IUserRepository` interface along with the necessary classes in a clear and organized manner:

  Step a : **Define the `IUserRepository` Interface**

Create an interface that outlines the methods for managing users.

```csharp
// File: Core/Interfaces/IUserRepository.cs

using System;
using System.Linq;
using System.Threading.Tasks;

namespace YourNamespace.Core.Interfaces
{
    public interface IUserRepository
    {
        IQueryable<User> GetUsers();
        Task<User> GetUserById(Guid id);
        Task<User> AddUser(User user);
        Task<User> UpdateUser(User user);
        Task DeleteUser(Guid id);
    }
}
```

  Step b: **Create the `User` Entity**

Define a simple `User` entity that the repository will manage.

```csharp
// File: Core/Entities/User.cs

using System;

namespace YourNamespace.Core.Entities
{
    public class User
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
    }
}
```

   Step c: **Set Up the `AppDbContext`**

Create the Entity Framework Core database context.

```csharp
// File: Infrastructure/Data/AppDbContext.cs

using Microsoft.EntityFrameworkCore;
using YourNamespace.Core.Entities;

namespace YourNamespace.Infrastructure.Data
{
    public class AppDbContext : DbContext
    {
        public AppDbContext(DbContextOptions<AppDbContext> options) : base(options)
        {
        }

        public DbSet<User> Users { get; set; }
    }
}
```

    Step d:  **Implement the `UserRepository` Class**
Create a repository class that implements the `IUserRepository` interface using Entity Framework Core.

```csharp
// File: Infrastructure/Data/UserRepository.cs

using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using YourNamespace.Core.Entities;
using YourNamespace.Core.Interfaces;

namespace YourNamespace.Infrastructure.Data
{
    public class UserRepository : IUserRepository
    {
        private readonly AppDbContext _context;

        public UserRepository(AppDbContext context)
        {
            _context = context;
        }

        public IQueryable<User> GetUsers()
        {
            return _context.Users;
        }

        public async Task<User> GetUserById(Guid id)
        {
            return await _context.Users.FindAsync(id);
        }

        public async Task<User> AddUser(User user)
        {
            _context.Users.Add(user);
            await _context.SaveChangesAsync();
            return user;
        }

        public async Task<User> UpdateUser(User user)
        {
            _context.Entry(user).State = EntityState.Modified;
            await _context.SaveChangesAsync();
            return user;
        }

        public async Task DeleteUser(Guid id)
        {
            var user = await _context.Users.FindAsync(id);
            if (user != null)
            {
                _context.Users.Remove(user);
                await _context.SaveChangesAsync();
            }
        }
    }
}
```
### 4. **Define Mutations:**
   - Create mutation classes for creating, updating, and deleting data.
     ```csharp
     public class Mutation
     {
         public async Task<User> CreateUser([Service] IUserRepository userRepository, CreateUserInput input)
         {
             var user = new User { Name = input.Name, Email = input.Email };
             return await userRepository.AddUser(user);
         }

         // Similar methods for update and delete
     }
     ```

### 5. **Configure GraphQL in Startup:**
   - Update your `Startup.cs` or `Program.cs` to configure GraphQL.
     ```csharp
     public void ConfigureServices(IServiceCollection services)
     {
         services.AddScoped<IUserRepository, UserRepository>();

         services
             .AddGraphQLServer()
             .AddQueryType<Query>()
             .AddMutationType<Mutation>()
             .AddType<UserType>();
     }

     public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
     {
         app.UseRouting();
         app.UseEndpoints(endpoints =>
         {
             endpoints.MapGraphQL();
         });
     }
     ```

### Additional Considerations

- **Authentication and Authorization:** Ensure that your GraphQL endpoints are secure. You can use middleware or attribute-based security.
- **Validation:** Implement validation for your GraphQL inputs.
- **Error Handling:** Provide meaningful error messages and handle exceptions gracefully.

---

**Comment by asifaliwork** [comment]
https://github.com/asifaliwork/CleanArchitectureDemo-net8.0- 

Crud with GraphQl Api (Comments)

**Comment by JMMAwais** [comment]
https://github.com/JMMAwais/CleanArchitectureWithRestAPI
