### ISSUE TITLE
Create a .NET Core API Application to Fetch Weather Data

### ISSUE THREAD

**Issue by abdullahkhanjmm** [abdullahkhanjmm/dotnet-roadmap-2024#13]
### Create a .NET Core API Application to Fetch Weather Data

**Task Overview:**

Create a .NET Core Web API application that calls the following open-source weather API endpoints to get weather updates for a specific location entered in the API input. The response should include temperature in Fahrenheit and Celsius, the name of the place, and the weather condition (e.g., sunny, cloudy, windy, etc.).

- [WeatherAPI](https://www.weatherapi.com/)
- [OpenWeatherMap](https://openweathermap.org/api)

**Steps to Complete the Task:**

1. **Project Setup:**
   - Create a new .NET Core Web API project using Visual Studio or the .NET CLI.
   - Name the project appropriately.

2. **Install NuGet Packages:**
   - Install `Newtonsoft.Json` for JSON serialization/deserialization.
   - Install `RestSharp` or use `HttpClient` for making HTTP requests.

3. **API Keys and Configuration:**
   - Register and obtain API keys from:
     - [WeatherAPI](https://www.weatherapi.com/)
     - [OpenWeatherMap](https://openweathermap.org/api)
   - Store these API keys securely in your application configuration (e.g., `appsettings.json` or environment variables).

4. **Create Models for Weather Data:**
   - Define classes to deserialize JSON responses from WeatherAPI and OpenWeatherMap.

5. **Create a Weather Service:**
   - Create a service that makes HTTP requests to both WeatherAPI and OpenWeatherMap endpoints.
   - The service should parse the response to extract:
     - Temperature in Fahrenheit and Celsius
     - Name of the place
     - Weather condition (e.g., sunny, cloudy, windy)

6. **Implement the Service Methods:**
   - Use the following endpoints to fetch weather data:
     - **WeatherAPI Endpoint:** `http://api.weatherapi.com/v1/current.json?key=YOUR_API_KEY&q=LOCATION`
     - **OpenWeatherMap Endpoint:** `http://api.openweathermap.org/data/2.5/weather?q=LOCATION&appid=YOUR_API_KEY`
   - Make sure to replace `YOUR_API_KEY` with your actual API keys and `LOCATION` with the location input.

7. **Create a Controller:**
   - Create a controller to handle incoming requests for weather updates.
   - The controller should accept location input from the user, call the weather service, and return the weather information.

8. **Format the Response:**
   - Structure the response to include:
     - Temperature in both Fahrenheit and Celsius
     - Name of the place
     - Weather condition

9. **Error Handling:**
   - Implement error handling for cases such as invalid API keys, incorrect location input, or failed API calls.
   - Provide user-friendly error messages.

10. **Testing:**
    - Test the API to ensure it correctly retrieves and returns the weather data from both endpoints.
    - Use tools like Postman or Swagger for testing.

**Sample Tasks:**

1. **Create Models:**
   - Create classes for deserializing responses from WeatherAPI and OpenWeatherMap.

2. **Implement Service:**
   - Implement methods to call the above endpoints and parse the required data.

3. **Create Controller:**
   - Develop a controller that accepts a location and returns the formatted weather data.

**Comment by asifaliwork** [comment]
https://github.com/asifaliwork/ThirdPartyAPIs

**Comment by JMMAwais** [comment]
https://github.com/JMMAwais/WeatherUpdates

**Comment by asifaliwork** [comment]
https://github.com/asifaliwork/ThirdPartyAPIs   

Second Part (Crud and aAuth Testing)
