### ISSUE TITLE
Hosting a Project on Azure

### ISSUE THREAD

**Issue by abdullahkhanjmm** [abdullahkhanjmm/dotnet-roadmap-2024#14]
---

#### Objective
Create an Azure account and host a project that includes database CRUD and API CRUD functionality. 

*Suggestion:* You can use the Clean Architecture project with GraphQL that you have previously worked on.

#### Steps

1. **Create an Azure Account**
   - Sign up for a free Azure account [here](https://azure.microsoft.com/en-us/free/).

2. **Set Up the Environment**
   - Install necessary tools (Azure CLI, any required SDKs, etc.).
   - Log in to Azure using the Azure CLI.

3. **Create a Resource Group**
   - Research how to create a resource group in Azure and create one for your project.

4. **Set Up a Database**
   - Research and create a suitable database on Azure.
   - Ensure the database is connected to your project.

5. **Deploy the Project**
   - Research how to deploy a .NET application to Azure.
   - Deploy your project to Azure.

6. **Configure the Application**
   - Ensure your application is correctly configured to connect to the database.
   - Make sure all CRUD operations (both database and API) are functional.

7. **Testing**
   - Test the deployed application to ensure all functionalities are working as expected.

8. **Submit**
   - Share the Azure resource links and any relevant access information.
   - Provide a link to the hosted application.

#### Expected Outcome
- A fully functional project with database CRUD and API CRUD hosted on Azure.

---

**Comment by asifaliwork** [comment]
https://cleanarchitecturegraphql.azurewebsites.net/graphql/

**Comment by JMMAwais** [comment]
https://achean.azurewebsites.net/graphql/
