### ISSUE TITLE
Options Pattern Implementation and Authentication Schemes 

### ISSUE THREAD

**Issue by abdullahkhanjmm** [abdullahkhanjmm/dotnet-roadmap-2024#15]
# ASP.NET Core Web Application Requirements

### Tasks
- **Create a new ASP.NET Core web application.**
- **Configure the authentication schemes in the `Startup.cs` file:**
  - Set Cookie Authentication as the default scheme.
- **Implement endpoints in a controller:**
  - An endpoint authenticated using Cookie Authentication.
  - An endpoint authenticated using JWT Authentication if the request header contains a Bearer token.
  - Endpoints with restricted authentication methods:
    - One endpoint allowing only Cookie Authentication.
    - One endpoint allowing only JWT Authentication.
- **Ensure proper configuration of authentication middleware and services** to handle both cookies and JWT tokens.
- **Access user data or roles based on the authentication scheme** used for each endpoint.
- **Test endpoints with valid authentication credentials** to verify functionality.
- **Provide clear documentation** on:
  - How to use and test the authentication schemes.
  - Information on endpoints with restricted authentication methods.

### Tasks
- **Create a custom class**, e.g., `AppSettings.cs`, to represent custom settings read from the `appsettings.json` file.
  - Define properties to match expected configuration values.
- **Configure binding of the AppSettings class to `appsettings.json`** in the `Startup.cs` file using the Options Pattern.
- **Implement loading strategies for accessing configuration values:**
  - **Eager Loading:**
    - Inject configuration options into a controller or service's constructor.
    - Access values within the constructor.
  - **Explicit Loading:**
    - Explicitly load configuration options within a specific method or property when needed.
  - **Lazy Loading:**
    - Use `IOptionsSnapshot` or `IOptionsMonitor` to lazily load configuration values and update them dynamically.
- **Provide examples** of accessing and using loaded configuration values in application logic.
- **Document steps for adding and modifying custom settings** in the `appsettings.json` file, including data types and constraints.

## Deliverables

- **Complete source code** of the web application, including:
  - Authentication implementations.
  - Options Pattern implementations.
- **Detailed documentation** on:
  - Setting up and testing authentication schemes.
  - Accessing custom settings in the `appsettings.json` file using the Options Pattern.

**Comment by JMMAwais** [comment]
https://github.com/JMMAwais/OptionPatternImplimentations

**Comment by asifaliwork** [comment]
https://github.com/asifaliwork/OptionsPattern_JWT_Cookies
