### ISSUE TITLE
Library System Console Application

### ISSUE THREAD

**Issue by abdullahkhanjmm** [abdullahkhanjmm/dotnet-roadmap-2024#3]
**Library System Console Application**

- This is an intermediate-level C# console application that simulates a Library System. It allows users to manage a library's collection of books and users.

**Task Description**
----
- You are tasked with building a Library System using C# and following object-oriented programming principles. The project involves creating dictionaries to manage books and users, implementing user-friendly interactions, and applying input validation. Here are the key components:

**Dictionaries**
----
- **BooksDictionary:** A dictionary representing the library's collection of books. Each book is associated with its ISBN as the key and contains properties like Title, Author, and Availability status.

- **UsersDictionary:** A dictionary representing the library's users. Each user is associated with their Library Card ID as the key and contains properties like Name.

**User Interaction**
----
**Users can:**

1. View a list of available books.
2. Borrow a book by entering their Library Card ID and the book's ISBN.
3. Return a book using their Library Card ID and the book's ISBN.
4. Add new books to the BooksDictionary (admin function).

**OOP Principles**
--

- Implement OOP principles like encapsulation, inheritance, and polymorphism as appropriate. Consider creating classes to represent books, users, and any other necessary entities.

**Input Validation**
--

- Ensure that the program handles invalid inputs gracefully and validates user inputs to prevent errors.

**Persistence (Optional)**
--
- Optionally, save the BooksDictionary and UsersDictionary to a file so that they can be loaded again when the program restarts.

**Usage**
--
- Provide instructions on how to run the Library System in your console application.

**Comment by asifaliwork** [comment]
https://github.com/asifaliwork/LibraryManagementSyste
