### ISSUE TITLE
Expense Tracker in MVC

### ISSUE THREAD

**Issue by abdullahkhanjmm** [abdullahkhanjmm/dotnet-roadmap-2024#4]
**Task: Develop an Expense Tracker with ViewModels in MVC**
--
**Objective:**
--
- Create an Expense Tracker application using ASP.NET MVC that tracks various expenses categorized into different items and expense categories. Utilize ViewModels to facilitate data transfer between the controller and the views.

**Project Structure:**
--
- The project will have three main models:

- **Item:** Represents the individual items purchased or expended.
- **ExpenseCategory:** Represents the category under which the expense falls (e.g., Food, Transportation, Entertainment).
- **Expense:** Represents the actual expense, linking items and categories along with the expense details.

**Database Context:**
--
- Set up a database context to manage the models and handle data persistence.

**Validation:**
--
- Implement server-side validation for the models where necessary.

**Documentation:**
--
Watch the Course Given for Reference

**Note : You have to create the project with latest Dotnet Version**

**Comment by asifaliwork** [comment]
https://github.com/asifaliwork/ExpenceTracker

**Comment by JMMAwais** [comment]
https://github.com/Awaiskiyani/ExpenseTracker
