### ISSUE TITLE
Task: Learn EF Core with N-Tier Architecture and Implement a Console and Web MVC Project

### ISSUE THREAD

**Issue by abdullahkhanjmm** [abdullahkhanjmm/dotnet-roadmap-2024#5]
**Objective:**
--
- Develop a comprehensive understanding of Entity Framework Core (EF Core) by implementing a console application with N-tier architecture. This task will cover various EF Core features such as DbContext, migrations, data seeding, data annotation, relationships, filtering queries, and Fluent API. Afterward, the same logic will be implemented in an ASP.NET MVC project.

**Project Structure:**

**N-tier Architecture:**
--
- **Data Access Layer (DAL):**  Contains DbContext, entity configurations, and repositories.
- **Business Logic Layer (BLL):**  Contains business logic and service classes.
- **Presentation Layer (PL):** Initially a console application, later extended to an ASP.NET MVC web application.

**EF Core Features:**
--
- **DbContext:** Manage database connections and entity configurations.
- **Migrations:** Manage database schema changes.
- **Data Seeding:** Initialize the database with initial data.
- **Data Annotation:** Use attributes to configure the model.
- **Relationships:** Define relationships between entities.
- **Filtering Query:** Query data with filters.
- **Fluent API:** Configure the model using the Fluent API.

**Tasks:**

Part 1: Console Application
**Set Up the Project:**
--
- Create a new .NET console application.
- Add EF Core and related packages.

**Define Models:**
--
- Create entity classes with properties.
- Use data annotations to configure entity properties.

**DbContext and Configuration:**
--
- Create a DbContext class to manage the database connection and DbSet properties.
- Configure entities using the Fluent API in the OnModelCreating method.

**Relationships:**
--
-Define relationships (one-to-one, one-to-many, many-to-many) using Fluent API and data annotations.

**Data Access Layer (DAL):**
--
- Create repository classes for CRUD operations.
- Implement generic repository pattern if applicable.

**Business Logic Layer (BLL):**
--
- Create service classes that use repositories to implement business logic.

**Data Seeding:**
--
- Implement data seeding to populate the database with initial data.

**Migrations:**
--
- Use EF Core migrations to create and update the database schema.

**Filtering Queries:**
--
- Implement various filtering queries to retrieve specific data.

**Console Application:**
--
- Create a console application that interacts with the BLL to perform CRUD operations and display data.

**Part 2: ASP.NET MVC Web Application**
**Set Up the Project:**
--
- Create a new ASP.NET MVC web application.
- Add EF Core and related packages.

**Reuse Logic from Console Application:**
--
- Reuse the existing models, DbContext, DAL, and BLL from the console application.

**Controllers and Views:**
--
- Create controllers to handle HTTP requests and interact with the BLL.
- Create views to display data and handle user input.

**CRUD Operations:**
--
- Implement CRUD operations using the same logic from the console application.
- Use view models if necessary to transfer data between controllers and views.

**Data Display and Filtering:**
--
- Create views to display data with filtering options.

**Testing and Validation:**
--
-Test the application to ensure all features work as expected.
- Implement server-side validation where necessary.

**Deliverables:**
--
**Console Application:**

- Fully functional console application demonstrating EF Core features.
- Properly commented code and organized folder structure.

**Web MVC Application:**

- Fully functional ASP.NET MVC application using the same EF Core logic.
- Properly commented code and organized folder structure.

Documentation:

- Please Watch the provided Course Tutorials for Task Reference.
- Feel free to ask questions if you need further clarifications. Good luck!

**Comment by JMMAwais** [comment]
https://github.com/Awaiskiyani/ConsoleEFCoreWithN_tier

**Comment by asifaliwork** [comment]
https://github.com/asifaliwork/NTierArchitecture-EF-Core-
