### ISSUE TITLE
Custome Validation Attribute

### ISSUE THREAD

**Issue by abdullahkhanjmm** [abdullahkhanjmm/dotnet-roadmap-2024#7]
- **You have to create a Validation attribute to validate a file such that the file has anyone of the extension from the specified extensions and size limit, it can also support multiples files or restrict it to only having specified no of files**

**Validation Conditions**
--
- If the Image Extension is incorrect then we show the following error,
![Screenshot 2024-07-01 102448](https://github.com/abdullahkhanjmm/dotnet-roadmap-2024/assets/156077319/1749aed9-ebec-459b-8cf6-a7905871cf8f)

- If the File Size Exceeds then our specified size then we show the following error,
![Screenshot 2024-07-01 102555](https://github.com/abdullahkhanjmm/dotnet-roadmap-2024/assets/156077319/60719e1d-2fad-4b21-bd17-4a59d6ff4b8d)

- If the Image Extension and size is valid, the image upload successfully,and we show the following message,
![3](https://github.com/abdullahkhanjmm/dotnet-roadmap-2024/assets/156077319/385c7e4f-3990-4386-b6c4-a3923d9f6cfb)

- The Application should Accept Multiple Files
![7](https://github.com/abdullahkhanjmm/dotnet-roadmap-2024/assets/156077319/7aff6032-62d6-4105-aa8c-94724c108995)

- The Application should throw an Exception if the numbers of files uploading exceeds our specified upload limit.
![Screenshot 2024-07-01 105719](https://github.com/abdullahkhanjmm/dotnet-roadmap-2024/assets/156077319/e58982e1-ef00-4f53-b1f0-19c49e47f7fb)

**Show List of All Uploaded Files and Files Detail (to view or Download File)**
--
- This Part is optional
![4](https://github.com/abdullahkhanjmm/dotnet-roadmap-2024/assets/156077319/856969f6-5e21-4b38-9adf-020a832047fd)
![5](https://github.com/abdullahkhanjmm/dotnet-roadmap-2024/assets/156077319/b641d3eb-c87a-4df3-8b1d-8b87d87fab37)

**Comment by asifaliwork** [comment]
https://github.com/asifaliwork/File-Validation-Attribute

**Comment by JMMAwais** [comment]
https://github.com/JMMAwais/FileUploadTaskV2
