### ISSUE TITLE
Interceptor Filter and Data Binding

### ISSUE THREAD

**Issue by abdullahkhanjmm** [abdullahkhanjmm/dotnet-roadmap-2024#8]
**Interceptor Filter and Data Binding**
--
**Overview**
**This repository provides solutions for two primary tasks:**

- **nterceptor Filter for Outgoing Responses:** A middleware to inspect and modify outgoing responses from action methods.
- **Data Binding using jQuery:** Binding data from multiple request data sources into an input object in various action methods.

**Contents**
--
**Interceptor Filter for Outgoing Responses**
**Objective:** Intercept outgoing response from an action and append specific details in the response headers.

- Action Name
- HTTP Method
- HTTP Scheme
- Host
- Port
- Time taken to execute
- Server date and time

**Data Binding using jQuery**
--
- **Objective:** Create multiple action methods and bind data from different request data sources into an input object using jQuery.

**Comment by JMMAwais** [comment]
https://github.com/JMMAwais/InterceptFilterDataBinding

**Comment by asifaliwork** [comment]
https://github.com/asifaliwork/Interceptor-Filter-and-Data-Binding
